spring:
  application:
    name: "Rotina Backend"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/rotina"
    username: "mysql"
    password: "mysql"
  
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

server:
  port: 8080
  servlet:
    context-path: "/api"
    
jwt:
  secret: "173763a94abd323bb04890e59f1611be"
  expiration: "86400000"

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: "always"
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState, db, diskSpace"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
