spring:
  application:
    name: "Rotina Backend"
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: ${spring_datasource_url}
    username: ${spring_datasource_username}
    password: ${spring_datasource_password}
  
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    hibernate:
      ddl-auto: "validate"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"

server:
  port: 8080
  servlet:
    context-path: "/api"
    
jwt:
  secret: ${jwt_secret}
  expiration: ${jwt_expiration}

amazon:
  access-key: ${amazon_access_key}
  secret-key: ${amazon_access_key}
  region: ${amazon_region}
  s3:
    bucket-name: ${amazon_s3_bucket_name}
    endpoint: ${amazon_s3_endpoint}

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: "always"
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState, db, diskSpace"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
